-- =======================================================
-- Supabase Database Schema for Mutafawweq Platform
-- منصة متفوق التعليمية - قواعد بيانات Supabase
-- =======================================================

-- 1. Create Questions Table (جدول بنك الأسئلة)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    unit_or_topic TEXT NOT NULL DEFAULT 'الوحدة العامة',
    question_text TEXT NOT NULL,
    question_type TEXT NOT NULL DEFAULT 'MCQ',
    option_a TEXT DEFAULT '',
    option_b TEXT DEFAULT '',
    option_c TEXT DEFAULT '',
    option_d TEXT DEFAULT '',
    correct_answer TEXT DEFAULT 'A',
    explanation TEXT DEFAULT '',
    difficulty TEXT DEFAULT 'متوسط',
    year_or_source TEXT DEFAULT 'سحابي من Supabase',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Feedbacks Table (جدول ملاحظات وبلاغات الطلاب)
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id TEXT PRIMARY KEY,
    question_id BIGINT,
    question_text TEXT,
    subject TEXT,
    selected_option TEXT,
    feedback_reason TEXT,
    note_text TEXT,
    status TEXT DEFAULT 'PENDING',
    timestamp BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Announcements Table (جدول الإعلانات والتنبيهات)
CREATE TABLE IF NOT EXISTS public.announcements (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    date TEXT DEFAULT 'الآن',
    is_important BOOLEAN DEFAULT false,
    timestamp BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) for public read/write or anon access
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (Anon key access)
CREATE POLICY "Allow anon read access on questions" ON public.questions FOR SELECT USING (true);
CREATE POLICY "Allow anon insert access on questions" ON public.questions FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon read access on feedbacks" ON public.feedbacks FOR SELECT USING (true);
CREATE POLICY "Allow anon insert access on feedbacks" ON public.feedbacks FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon read access on announcements" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Allow anon insert access on announcements" ON public.announcements FOR INSERT WITH CHECK (true);

-- Insert Sample Questions into Supabase
INSERT INTO public.questions (subject, unit_or_topic, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, year_or_source)
VALUES 
('MATH', 'الدوال الأسية واللوغاريتمية', 'لتكن الدالة f(x) = (2x - 1)e^x. إن مشتقة الدالة f''(x) تساوي:', 'MCQ', '(2x + 1)e^x', '(2x - 1)e^x', '2e^x', '(x + 2)e^x', 'A', 'باستخدام قاعدة مشتق الجداء (u.v)'' = u''v + uv: f''(x) = 2e^x + (2x - 1)e^x = (2x + 1)e^x.', 'متوسط', 'بكالوريا 2023 الدورة العادية'),
('PHYSICS', 'الكهرباء والمكثفات', 'في دارة RC، ثابت الزمن τ يساوي بالجداء:', 'MCQ', 'R × C', 'R / C', 'C / R', '1 / (RC)', 'A', 'ثابت الزمن في دارة الشحن والتفريغ هو τ = RC وله بعد زمني يقدر بالثانية (s).', 'سهل', 'بكالوريا 2022 تجريبي'),
('SCIENCE', 'تركيب البروتين والترجمة', 'تتم عملية الترجمة عند حقيقيات النوى في:', 'MCQ', 'الهيولى (السيتوبلازم) على مستوى الريبوزومات', 'داخل النواة فقط', 'داخل الميتوكوندريا فقط', 'في الغشاء الهيولي الخارجي', 'A', 'تتم عملية الاستنساخ داخل النواة بينما تتم عملية الترجمة في الهيولى بتدخل الريبوزومات و ARNt.', 'متوسط', 'وزاري 2021');
